Repository CST438Fall2024/FrontEndProject2, pull requests merged in 2024-10, with the labels that each got.

#12 Landing Page Starter Code
  project2group6/package-lock.json
  project2group6/src/App.css
  project2group6/src/App.js
Labels: Simple

#13 Initialized Item page
  project2group6/src/App.test.js
  project2group6/src/css/List.css
  project2group6/src/index.js
  project2group6/src/pages/AddItem.js
  project2group6/src/pages/List.js
Labels: Simple

#17 User login and sign up
  project2group6/package-lock.json
  project2group6/package.json
  project2group6/public/index.html
  project2group6/src/css/App.css
  project2group6/src/pages/App.js
Labels: BackendNeeded

#18 Implementing Google Login
  project2group6/public/index.html
  project2group6/src/pages/App.js
Labels: Middle

#19 Added profile backend logic and additem page template
  project2group6/package-lock.json
  project2group6/package.json
  project2group6/src/Layout.js
  project2group6/src/css/AddItem.css
  project2group6/src/css/Layout.css
  project2group6/src/css/List.css
  project2group6/src/css/Profile.css
  project2group6/src/index.js
  project2group6/src/pages/AddItem.js
  project2group6/src/pages/Admin.js
  project2group6/src/pages/List.js
  project2group6/src/pages/Profile.js
Labels: Middle, BackendNeeded

#32 Sessions
  project2group6/package-lock.json
  project2group6/package.json
  project2group6/public/favicon.ico
  project2group6/public/index.html
  project2group6/public/logo192.png
  project2group6/public/logo512.png
  project2group6/src/Layout.js
  project2group6/src/pages/Admin.js
  project2group6/src/pages/App.js
  project2group6/yarn.lock
Labels: BackendNeeded

#34 Profile, Wishlist, Items
  project2group6/src/index.js
  project2group6/src/pages/List.js
  project2group6/src/pages/ListContent.js
  project2group6/src/pages/Profile.js
Labels: Difficult

#36 Edit wishlist itemsand main wishlist
  project2group6/package-lock.json
  project2group6/package.json
  project2group6/src/css/AddItem.css
  project2group6/src/css/admin.css
  project2group6/src/index.js
  project2group6/src/logo.svg
  project2group6/src/pages/AddItem.js
  project2group6/src/pages/Admin.js
  project2group6/src/pages/App.js
  project2group6/src/pages/List.js
  project2group6/src/pages/ListContent.js
  project2group6/src/pages/Profile.js
  project2group6/yarn.lock
Labels: Middle

#38 Looks and checks
  project2group6/src/Media/pexels-content-pixie-1405717-2736499.jpg
  project2group6/src/css/AddItem.css
  project2group6/src/css/App.css
  project2group6/src/css/Layout.css
  project2group6/src/css/List.css
  project2group6/src/css/Profile.css
  project2group6/src/css/admin.css
  project2group6/src/pages/AddItem.js
  project2group6/src/pages/Admin.js
  project2group6/src/pages/App.js
  project2group6/src/pages/List.js
  project2group6/src/pages/ListContent.js
  project2group6/src/pages/Profile.js
Labels: Simple
